config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do 
  
  resources :blog_posts
  get 'admins/index'
  root to: 'admins#index'
  end

  get 'home/index'
  
  resources :blog_posts 

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    belongs_to :blog_post
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_one :author
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
    def index
        @blog_posts = BlogPost.all 
    end
    def show
        @blog_post = BlogPost.find(params[:id])
    end
    def new
    end
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.all.order(:updated_at).reverse 
  end
  def show
    @blog_post = BlogPost.find(params[:id])
  end 

  def new
    @blog_post = BlogPost.new 
  end 

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

     if @blog_post.save
    redirect_to @blog_post
     else 
      render 'new'
     end 
  end

  def update
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render 'edit'
    end
  end 

  def destroy 
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    redirect_to admin_root_path
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :excerpt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.all.order(:updated_at).reverse 
  end
  def show
    @blog_post = BlogPost.find(params[:id])
  end 

  def new
    @blog_post = BlogPost.new 
  end 

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

     if @blog_post.save
    redirect_to @blog_post
     else 
      render 'new'
     end 
  end

  def update
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render 'edit'
    end
  end 

  def destroy 
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    redirect_to admin_root_path
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :excerpt)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @blog_posts = BlogPost.all.order(:updated_at).reverse
    end
    def show
        @blog_post = BlogPost.find(params[:id])
    end
    def new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/index.html.erb
<h1>This is admins</h1>
<%= link_to 'New Posts', new_admin_blog_post_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @blog_posts.each do |blog_post| %>
    <tr>
      <td><%= blog_post.title %></td>
      <td><%= blog_post.excerpt %></td>
      <td><%= blog_post.content %></td>
      <td><%= link_to 'Show', blog_post_path(blog_post) %></td>
      <td><%= link_to 'Edit', edit_admin_blog_post_path(blog_post) %></td>
      <td><%= link_to 'Destroy', blog_post_path(blog_post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/admin/blog_posts/edit.html.erb
<h1>Edit Blog Post </h1>

<%= form_with(model: @blog_post, local: true) do |form| %>
    <p>
        <%= form.label :title %></br>
        <%= form.text_field :title %>
    </p>


    <p>
        <%= form.label :excerpt %></br>
        <%= form.text_area :excerpt %>
    </p>

    <p>
        <%= form.label :content %></br>
        <%= form.text_area :content %>
    </p>

    <p>
        <%= form.submit %>
    </p>

<% end %>

<%= link_to 'Back', blog_posts_path %>

app/views/admin/blog_posts/index.html.erb
<h1>ALL BLOG POSTS</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @blog_posts.each do |blog_post| %>
    <tr>
      <td><%= blog_post.title %></td>
      <td><%= blog_post.excerpt %></td>
      <td><%= link_to 'Show', blog_post_path(blog_post) %></td>
    </tr>
  <% end %>
</table>

app/views/admin/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<%= form_with scope: :blog_post, url: blog_posts_path, local: true do |form| %>
<p> 
    <%= form.label :title %><br>
    <%= form.text_field :title %>
</p>

<p>
    <%= form.label :excerpt %></br>
    <%= form.text_area :excerpt %>
</p>

<p> 
    <%= form.label :content %><br>
    <%= form.text_area :content %>
</p>

<p>
    <%= form.submit %>
</p>
<% end %>
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p> 
    <strong>Title:</strong>
    <%= @blog_post.title %>
</p>


<p> 
    <strong>Content:</strong>
    <%= @blog_post.content %>
</p>
<%= link_to 'Back', blog_posts_path %>

app/views/home/index.html.erb
<link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet">
<div class="display">
  <div class="body-text">
    <section class="section-layout">
      <h1>Films? I've seen them.</h1>
    </section>
    <section class="section-layout">
      <table>
        <% @blog_posts.each do |blog_post| %>
          <tr class="section-layout">
            <td class="title"><%= blog_post.title %></td>
            <td><%= blog_post.excerpt %></td>
            <td><%= link_to ' More here!', blog_post_path(blog_post) %></td>
          </tr>
        <% end %>
      </table>
    </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>